version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: crit-fumble-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: crit_fumble
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crit_fumble"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local