# FumbleBot deployment configuration for Fly.io
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fumblebot-crit-fumble-com"
primary_region = "den"

[build]
  dockerfile = "Dockerfile.bot"

[env]
  NODE_VERSION = "22"
  BOT_PATH = "dist/bot"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.ports]]
  port = 3001
  handlers = ["http"]
  force_https = true
