name: Discord Event Monitor

on:
  schedule:
    # Run every 2 minutes (pushing GitHub's limits but may work)
    - cron: '*/2 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  check-discord-events:
    runs-on: ubuntu-latest
    steps:
      - name: Check Discord Events
        run: |
          curl -X GET "https://www.crit-fumble.com/api/discord/cron" \
            -H "User-Agent: GitHub-Actions-Cron" \
            -f || echo "Cron endpoint failed, but continuing..."
      
      - name: Log execution
        run: echo "Discord event check completed at $(date)"